--- 
- 
  apt: 
    update_cache: true
  become: true
  name: "update apt packages."
- 
  apt: 
    upgrade: true
  become: true
  name: "upgrade packages"
- 
  apt: 
    autoremove: true
  become: true
  name: "remove dependencies that are no longer required"
- 
  apt: 
    name: 
      - nodejs
      - npm
    state: latest
    update_cache: true
  become: true
  name: "install dependencies."
- 
  become: true
  name: "install pm2"
  npm: 
    global: true
    name: pm2
    production: true
    state: present
- 
  file: 
    path: ~/web
    state: directory
  name: "Creates directory"
- 
  name: "Copy index test page"
  template: 
    dest: ~/web/index.js
    src: files/index.js
- 
  name: "Executing node"
  shell: "pm2 start ~/web/index.js -f"
